AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/*.gemspec'
    - '**/Rakefile'
    - 'exe/*'
  Exclude:
    - vendor/**/*
    - db/migrations/**/*

  DisplayCopNames:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 60
