#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'swr3_now_playing/loader'
require 'swr3_now_playing/mapper'

json = SWR3::NowPlaying::Loader.load

begin
  song = SWR3::NowPlaying::Mapper.map(json)
  puts "#{Time.new} - #{song}"
rescue JSON::ParserError => e
  warn "Error parsing JSON response: #{e.message}"
  warn 'Offending document is: '
  warn json

  exit 1
end
